name: zuarte
description: "Zuarte é um reprodutor de música moderno, minimalista e com uma identidade única. Criado com Flutter + Dart."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sizer: ^3.0.5
  iconify_flutter: ^0.0.7
  miniplayer: ^1.0.1
  just_audio: ^0.10.4
  scrollable_positioned_list: ^0.3.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  on_audio_query: ^2.9.0

dependency_overrides:
  on_audio_query_android:
    path: ./android/plugins/on_audio_query_android

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
 
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf  
          weight: 700